export type FieldCandidates=readonly string[];
export type RawListItem=Record<string,string|number|boolean|null>;
export const NONCONFORMITY_FIELD_MAP={number:["UygunsuzlukNumarasi","Title","NCNumber"],type:["UygunsuzlukTipi","NCType"],detectedAt:["UygunsuzlukTespitTarihi","TespitTarihi","DetectedDate"],subject:["UygunsuzlukKonusu","Konu","Subject"],station:["UreticiFirmaIstasyon","Istasyon","Station"],description:["TespitEdilenUygunsuzluk","Aciklama","Description"],detectionMethod:["UygunsuzlugunTespitSekli","TespitSekli","DetectionMethod"],isAccepted:["UygunsuzlukOlarakDegerlendirilsinMi","Degerlendirme","IsNonconformity"],owner:["Sorumlu","Owner","AssignedTo"],actionOwner:["AksiyonAlan","ActionOwner"],category:["Kategori","Category"],projectCode:["ProjeKodu","ProjectCode"],affectsProject:["ProjeyiEtkiliyorMu","AffectsProject"],status:["Durum","Status"],openedAt:["AcilisTarihi","Created","OpenedDate"],closedAt:["KapanisTarihi","ClosedDate"],department:["Departman","Department"],severity:["OnemDerecesi","Severity"],dueDate:["TerminTarihi","DueDate"],quantityAffected:["EtkilenenAdet","Quantity"],reportedBy:["TespitEden","ReportedBy"],workOrder:["IsEmri","WorkOrder"]} as const satisfies Record<string,FieldCandidates>;
export const ROOT_CAUSE_FIELD_MAP={nonconformityNumber:["UygunsuzlukNumarasi","Title","NCNumber"],startedAt:["AnalizeBaslanmaTarihi","BaslangicTarihi","StartDate"],rootCause:["KokNeden","RootCause"],possibleCauses:["OlasiNedenler","PossibleCauses"],proposedSolutions:["CozumOnerileri","ProposedSolutions"],decision:["Karar","Decision"],performedAction:["GerceklestirilenFaaliyet","Faaliyet","PerformedAction"],closedAt:["KapanisTarihi","ClosedDate"],closingNote:["KapanisBilgisi","KapanisNotu","ClosingNote"],submittedBy:["AnaliziYapan","SubmittedBy"],effectiveness:["Etkinlik","Effectiveness"]} as const satisfies Record<string,FieldCandidates>;
export function readField(item:Record<string,unknown>,candidates:FieldCandidates){for(const key of candidates){const value=item[key];if(value!==undefined&&value!==null&&value!=="")return value;}return undefined;}
export function readString(item:Record<string,unknown>,candidates:FieldCandidates,fallback=""){const value=readField(item,candidates);if(value===undefined)return fallback;if(typeof value==="object"&&value!==null){const lookup=value as Record<string,unknown>;const label=lookup.Title??lookup.LookupValue??lookup.DisplayName;if(typeof label==="string")return label;}return String(value);}
export function readNumber(item:Record<string,unknown>,candidates:FieldCandidates,fallback=0){const value=Number(readField(item,candidates));return Number.isFinite(value)?value:fallback;}
export function readBoolean(item:Record<string,unknown>,candidates:FieldCandidates){const value=readField(item,candidates);if(value===undefined)return null;if(typeof value==="boolean")return value;const text=String(value).trim().toLowerCase();if(["evet","yes","true","1","var"].includes(text))return true;if(["hayır","hayir","no","false","0","yok"].includes(text))return false;return null;}
export function readDate(item:Record<string,unknown>,candidates:FieldCandidates){const value=readField(item,candidates);if(value===undefined)return null;const date=new Date(String(value));return Number.isNaN(date.getTime())?null:date.toISOString();}
export const NONCONFORMITY_FIELD_LABELS={number:"Uygunsuzluk Numarası",type:"Uygunsuzluk Tipi",detectedAt:"Tespit Tarihi",subject:"Uygunsuzluk Konusu",station:"Üretici Firma / İstasyon",description:"Tespit Edilen Uygunsuzluk",detectionMethod:"Tespit Şekli",isAccepted:"Uygunsuzluk Olarak Değerlendirilsin mi",owner:"Sorumlu",actionOwner:"Aksiyon Alan",category:"Kategori",projectCode:"Proje Kodu",affectsProject:"Projeyi Etkiliyor mu",status:"Durum",openedAt:"Açılış Tarihi",closedAt:"Kapanış Tarihi",department:"Departman",severity:"Önem Derecesi",dueDate:"Termin Tarihi",quantityAffected:"Etkilenen Adet",reportedBy:"Tespit Eden",workOrder:"İş Emri"} as Record<keyof typeof NONCONFORMITY_FIELD_MAP,string>;
export const ROOT_CAUSE_FIELD_LABELS={nonconformityNumber:"Uygunsuzluk Numarası",startedAt:"Analize Başlanma Tarihi",rootCause:"Kök Neden",possibleCauses:"Olası Nedenler",proposedSolutions:"Çözüm Önerileri",decision:"Karar",performedAction:"Gerçekleştirilen Faaliyet",closedAt:"Kapanış Tarihi",closingNote:"Kapanış Bilgisi",submittedBy:"Analizi Yapan",effectiveness:"Etkinlik"} as Record<keyof typeof ROOT_CAUSE_FIELD_MAP,string>;
export const NONCONFORMITY_REQUIRED_FIELDS=["number","subject","station","status","openedAt","owner","category"] as const;
export const ROOT_CAUSE_REQUIRED_FIELDS=["nonconformityNumber","rootCause"] as const;
export type FieldMatchStatus="matched"|"missing"|"check";
export interface FieldMatchResult{key:string;label:string;listField:string;candidates:string[];required:boolean;status:FieldMatchStatus;note:string;}
export function validateFieldMap<K extends string>(columnNames:readonly string[],map:Record<K,FieldCandidates>,labels:Record<K,string>,required:readonly K[]):FieldMatchResult[]{const available=new Set(columnNames);return (Object.keys(map) as K[]).map(key=>{const candidates=[...map[key]];const found=candidates.find(c=>available.has(c));const isRequired=required.includes(key);let status:FieldMatchStatus;let note="";if(found&&found===candidates[0])status="matched";else if(found){status="check";note=`Yedek sütun kullanılıyor (${found}); doğru alan olduğu teyit edilmeli.`;}else if(isRequired){status="missing";note=`Beklenen sütunlardan hiçbiri yok: ${candidates.join(", ")}`;}else{status="check";note="Opsiyonel alan listede yok; varsayılan değer kullanılacak.";}return{key,label:labels[key],listField:found??candidates[0]??"",candidates,required:isRequired,status,note};});}
