const GRAPH_BASE="https://graph.microsoft.com/v1.0";
const TOKEN_HOST="https://login.microsoftonline.com";
export interface GraphConfig {tenantId:string;clientId:string;clientSecret:string;siteId:string;nonconformityListId:string;rootCauseListId:string;}
export const GRAPH_ENV_VARS={MS_GRAPH_TENANT_ID:"tenantId",MS_GRAPH_CLIENT_ID:"clientId",MS_GRAPH_CLIENT_SECRET:"clientSecret",MS_SHAREPOINT_SITE_ID:"siteId",MS_LIST_NONCONFORMITIES_ID:"nonconformityListId",MS_LIST_ROOT_CAUSES_ID:"rootCauseListId"} as const satisfies Record<string,keyof GraphConfig>;
export type GraphErrorCode="not_configured"|"auth_failed"|"site_not_found"|"list_not_found"|"fetch_failed";
export class GraphError extends Error { constructor(public readonly code:GraphErrorCode,message:string,public readonly detail=""){super(message);this.name="GraphError";} }
export function getMissingEnvVars(){return Object.keys(GRAPH_ENV_VARS).filter(n=>!process.env[n]?.trim());}
export function readGraphConfig():GraphConfig {const missing=getMissingEnvVars();if(missing.length)throw new GraphError("not_configured","Bağlantı yapılandırılmamış",`Eksik ortam değişkenleri: ${missing.join(", ")}`);const c={} as GraphConfig;for(const [n,k] of Object.entries(GRAPH_ENV_VARS))c[k]=process.env[n]!.trim();return c;}
async function describeError(response:Response){try{const json=await response.json() as {error?:{code?:string;message?:string}|string;error_description?:string};if(typeof json.error==="object"&&json.error)return `HTTP ${response.status} · ${json.error.code??""} ${json.error.message??""}`.trim();return `HTTP ${response.status} · ${String(json.error??"")} ${(json.error_description??"").split("\r\n")[0]}`.trim();}catch{return `HTTP ${response.status}`;}}
export async function getAccessToken(config:GraphConfig){let response:Response;try{response=await fetch(`${TOKEN_HOST}/${encodeURIComponent(config.tenantId)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,scope:"https://graph.microsoft.com/.default",grant_type:"client_credentials"})});}catch(error){throw new GraphError("auth_failed","Kimlik doğrulama başarısız",String(error));}if(!response.ok)throw new GraphError("auth_failed","Kimlik doğrulama başarısız",await describeError(response));const json=await response.json() as {access_token?:string};if(!json.access_token)throw new GraphError("auth_failed","Kimlik doğrulama başarısız","Erişim jetonu dönmedi.");return json.access_token;}
async function graphGet<T>(token:string,url:string,notFound:GraphError):Promise<T>{let response:Response;try{response=await fetch(url.startsWith("http")?url:`${GRAPH_BASE}${url}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"}});}catch(error){throw new GraphError("fetch_failed","Veri alınamadı",String(error));}if(response.status===404||response.status===400)throw new GraphError(notFound.code,notFound.message,await describeError(response));if(response.status===401||response.status===403)throw new GraphError("auth_failed","Kimlik doğrulama başarısız",`${await describeError(response)} — Sites.Read.All izni ve yönetici onayı kontrol edilmeli.`);if(!response.ok)throw new GraphError("fetch_failed","Veri alınamadı",await describeError(response));return await response.json() as T;}
export async function getSite(token:string,config:GraphConfig){return graphGet<{id:string;displayName?:string;webUrl?:string}>(token,`/sites/${config.siteId}`,new GraphError("site_not_found","SharePoint sitesi bulunamadı"));}
export async function getListWithColumns(token:string,config:GraphConfig,listId:string){return graphGet<{id:string;displayName?:string;columns?:{name:string;displayName?:string}[]}>(token,`/sites/${config.siteId}/lists/${encodeURIComponent(listId)}?expand=columns`,new GraphError("list_not_found","Liste bulunamadı",`Liste: ${listId}`));}
export async function fetchListItems(config:GraphConfig,listId:string,token?:string){const accessToken=token??await getAccessToken(config);const items:Record<string,unknown>[]=[];let url:string|undefined=`/sites/${config.siteId}/lists/${encodeURIComponent(listId)}/items?expand=fields&$top=200`;while(url){const page=await graphGet<{value?:{fields?:Record<string,unknown>}[];"@odata.nextLink"?:string}>(accessToken,url,new GraphError("list_not_found","Liste bulunamadı",`Liste: ${listId}`));for(const entry of page.value??[])if(entry.fields)items.push(entry.fields);url=page["@odata.nextLink"];}return items;}
