import {DEPARTMENTS,FAILURE_CATEGORIES,FAILURE_FAMILIES,PRODUCTION_STATIONS,SEVERITIES,WORKFLOW_STATUSES} from "../../domain/constants";
import type {Department,FailureCategory,Nonconformity,ProductionStation,RootCauseAnalysis,Severity,WorkflowStatus} from "../../domain/types";
import {NONCONFORMITY_FIELD_MAP,ROOT_CAUSE_FIELD_MAP,readBoolean,readDate,readNumber,readString} from "./field-mapping";
import {normalizeNcNumber} from "./nc-number";
function normalizeKey(value:string){return value.trim().toLocaleLowerCase("tr");}
function matchOption<T extends string>(value:string,options:readonly T[],fallback:T):T{if(!value)return fallback;const key=normalizeKey(value);const exact=options.find(o=>normalizeKey(o)===key);if(exact)return exact;const partial=options.find(o=>normalizeKey(o).includes(key)||key.includes(normalizeKey(o)));return partial??fallback;}
export function normalizeNonconformity(item:Record<string,unknown>):Nonconformity{const number=readString(item,NONCONFORMITY_FIELD_MAP.number);const key=normalizeNcNumber(number);const openedAt=readDate(item,NONCONFORMITY_FIELD_MAP.openedAt)??readDate(item,NONCONFORMITY_FIELD_MAP.detectedAt)??new Date().toISOString();const closedAt=readDate(item,NONCONFORMITY_FIELD_MAP.closedAt);const dueDate=readDate(item,NONCONFORMITY_FIELD_MAP.dueDate)??new Date(new Date(openedAt).getTime()+14*86400000).toISOString();const status=matchOption<WorkflowStatus>(readString(item,NONCONFORMITY_FIELD_MAP.status),WORKFLOW_STATUSES,closedAt?"Closed":"New");return{id:key?`nc-${key}`:`nc-${readString(item,["id","ID"],crypto.randomUUID())}`,code:number,ncNumber:number,title:readString(item,NONCONFORMITY_FIELD_MAP.subject,"Uygunsuzluk"),description:readString(item,NONCONFORMITY_FIELD_MAP.description),station:matchOption<ProductionStation>(readString(item,NONCONFORMITY_FIELD_MAP.station),PRODUCTION_STATIONS,PRODUCTION_STATIONS[0]),department:matchOption<Department>(readString(item,NONCONFORMITY_FIELD_MAP.department),DEPARTMENTS,DEPARTMENTS[0]),category:matchOption<FailureCategory>(readString(item,NONCONFORMITY_FIELD_MAP.category),FAILURE_CATEGORIES,FAILURE_CATEGORIES[0]),failureFamily:FAILURE_FAMILIES[0],severity:matchOption<Severity>(readString(item,NONCONFORMITY_FIELD_MAP.severity),SEVERITIES,"Medium"),status,openedAt,dueDate,closedAt,reportedBy:readString(item,NONCONFORMITY_FIELD_MAP.reportedBy,"—"),assignedTo:readString(item,NONCONFORMITY_FIELD_MAP.owner,"—"),productCode:readString(item,NONCONFORMITY_FIELD_MAP.projectCode),quantityAffected:readNumber(item,NONCONFORMITY_FIELD_MAP.quantityAffected,1),workOrder:readString(item,NONCONFORMITY_FIELD_MAP.workOrder),nonconformityType:readString(item,NONCONFORMITY_FIELD_MAP.type),detectedAt:readDate(item,NONCONFORMITY_FIELD_MAP.detectedAt),detectionMethod:readString(item,NONCONFORMITY_FIELD_MAP.detectionMethod),isAccepted:readBoolean(item,NONCONFORMITY_FIELD_MAP.isAccepted),actionOwner:readString(item,NONCONFORMITY_FIELD_MAP.actionOwner),projectCode:readString(item,NONCONFORMITY_FIELD_MAP.projectCode),affectsProject:readBoolean(item,NONCONFORMITY_FIELD_MAP.affectsProject)};}
export function normalizeRootCause(item:Record<string,unknown>,index:number):RootCauseAnalysis{const number=readString(item,ROOT_CAUSE_FIELD_MAP.nonconformityNumber);const key=normalizeNcNumber(number);return{id:`rca-${key||index}`,nonconformityId:key?`nc-${key}`:"",nonconformityNumber:number,method:"5 Why",rootCause:readString(item,ROOT_CAUSE_FIELD_MAP.rootCause),correctiveAction:readString(item,ROOT_CAUSE_FIELD_MAP.performedAction),preventiveAction:readString(item,ROOT_CAUSE_FIELD_MAP.proposedSolutions),submittedBy:readString(item,ROOT_CAUSE_FIELD_MAP.submittedBy,"—"),submittedAt:readDate(item,ROOT_CAUSE_FIELD_MAP.startedAt)??new Date().toISOString(),approvedAt:readDate(item,ROOT_CAUSE_FIELD_MAP.closedAt),effectiveness:"Pending",startedAt:readDate(item,ROOT_CAUSE_FIELD_MAP.startedAt),possibleCauses:readString(item,ROOT_CAUSE_FIELD_MAP.possibleCauses),proposedSolutions:readString(item,ROOT_CAUSE_FIELD_MAP.proposedSolutions),decision:readString(item,ROOT_CAUSE_FIELD_MAP.decision),performedAction:readString(item,ROOT_CAUSE_FIELD_MAP.performedAction),closingNote:readString(item,ROOT_CAUSE_FIELD_MAP.closingNote)};}
export function linkRootCauses(records:Nonconformity[],rootCauses:RootCauseAnalysis[]){const byNumber=new Map(records.map(r=>[normalizeNcNumber(r.ncNumber??r.code),r.id]));return rootCauses.map(rca=>{const key=normalizeNcNumber(rca.nonconformityNumber);const id=key?byNumber.get(key):undefined;return id?{...rca,nonconformityId:id}:rca;});}
